# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lance.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'lance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import leilao_pb2 as leilao__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blance.proto\x12\x05lance\x1a\x0cleilao.proto\">\n\tLanceData\x12\x11\n\tleilao_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05valor\x18\x03 \x01(\x02\"0\n\rLanceResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\",\n\x06\x45vento\x12\x0c\n\x04tipo\x18\x01 \x01(\t\x12\x14\n\x0cpayload_json\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\xa5\x02\n\x0cLanceService\x12\x38\n\x0eProcessarLance\x12\x10.lance.LanceData\x1a\x14.lance.LanceResponse\x12\x35\n\x0fGetLancesAtuais\x12\x0c.lance.Empty\x1a\x12.leilao.LeilaoData0\x01\x12\x39\n\x15NotificarInicioLeilao\x12\x12.leilao.LeilaoData\x1a\x0c.lance.Empty\x12\x36\n\x12NotificarFimLeilao\x12\x12.leilao.LeilaoData\x1a\x0c.lance.Empty\x12\x31\n\x10SubscribeEventos\x12\x0c.lance.Empty\x1a\r.lance.Evento0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LANCEDATA']._serialized_start=36
  _globals['_LANCEDATA']._serialized_end=98
  _globals['_LANCERESPONSE']._serialized_start=100
  _globals['_LANCERESPONSE']._serialized_end=148
  _globals['_EVENTO']._serialized_start=150
  _globals['_EVENTO']._serialized_end=194
  _globals['_EMPTY']._serialized_start=196
  _globals['_EMPTY']._serialized_end=203
  _globals['_LANCESERVICE']._serialized_start=206
  _globals['_LANCESERVICE']._serialized_end=499
# @@protoc_insertion_point(module_scope)
