# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: leilao.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'leilao.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cleilao.proto\x12\x06leilao\"\x84\x01\n\nLeilaoData\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tdescricao\x18\x02 \x01(\t\x12\x15\n\rvalor_inicial\x18\x03 \x01(\x02\x12\x0e\n\x06inicio\x18\x04 \x01(\t\x12\x0b\n\x03\x66im\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t\x12\x13\n\x0bvalor_atual\x18\x07 \x01(\x02\",\n\x06\x45vento\x12\x0c\n\x04tipo\x18\x01 \x01(\t\x12\x14\n\x0cpayload_json\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\xb5\x01\n\x0e\x41uctionService\x12\x35\n\x0b\x43riarLeilao\x12\x12.leilao.LeilaoData\x1a\x12.leilao.LeilaoData\x12\x37\n\x10GetLeiloesAtivos\x12\r.leilao.Empty\x1a\x12.leilao.LeilaoData0\x01\x12\x33\n\x10SubscribeEventos\x12\r.leilao.Empty\x1a\x0e.leilao.Evento0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'leilao_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LEILAODATA']._serialized_start=25
  _globals['_LEILAODATA']._serialized_end=157
  _globals['_EVENTO']._serialized_start=159
  _globals['_EVENTO']._serialized_end=203
  _globals['_EMPTY']._serialized_start=205
  _globals['_EMPTY']._serialized_end=212
  _globals['_AUCTIONSERVICE']._serialized_start=215
  _globals['_AUCTIONSERVICE']._serialized_end=396
# @@protoc_insertion_point(module_scope)
