# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import leilao_pb2 as leilao__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in leilao_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuctionServiceStub(object):
    """--- Definição dos Serviços (Interfaces gRPC) ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CriarLeilao = channel.unary_unary(
                '/leilao.AuctionService/CriarLeilao',
                request_serializer=leilao__pb2.LeilaoData.SerializeToString,
                response_deserializer=leilao__pb2.LeilaoData.FromString,
                _registered_method=True)
        self.GetLeiloesAtivos = channel.unary_stream(
                '/leilao.AuctionService/GetLeiloesAtivos',
                request_serializer=leilao__pb2.Empty.SerializeToString,
                response_deserializer=leilao__pb2.LeilaoData.FromString,
                _registered_method=True)
        self.SubscribeEventos = channel.unary_stream(
                '/leilao.AuctionService/SubscribeEventos',
                request_serializer=leilao__pb2.Empty.SerializeToString,
                response_deserializer=leilao__pb2.Evento.FromString,
                _registered_method=True)


class AuctionServiceServicer(object):
    """--- Definição dos Serviços (Interfaces gRPC) ---

    """

    def CriarLeilao(self, request, context):
        """Cria um leilão e retorna seus dados.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLeiloesAtivos(self, request, context):
        """Retorna um fluxo (stream) de leilões ativos (Server Streaming).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEventos(self, request, context):
        """Mantém um canal aberto enviando eventos do MS Leilão para o Gateway.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuctionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CriarLeilao': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarLeilao,
                    request_deserializer=leilao__pb2.LeilaoData.FromString,
                    response_serializer=leilao__pb2.LeilaoData.SerializeToString,
            ),
            'GetLeiloesAtivos': grpc.unary_stream_rpc_method_handler(
                    servicer.GetLeiloesAtivos,
                    request_deserializer=leilao__pb2.Empty.FromString,
                    response_serializer=leilao__pb2.LeilaoData.SerializeToString,
            ),
            'SubscribeEventos': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEventos,
                    request_deserializer=leilao__pb2.Empty.FromString,
                    response_serializer=leilao__pb2.Evento.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'leilao.AuctionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('leilao.AuctionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuctionService(object):
    """--- Definição dos Serviços (Interfaces gRPC) ---

    """

    @staticmethod
    def CriarLeilao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/leilao.AuctionService/CriarLeilao',
            leilao__pb2.LeilaoData.SerializeToString,
            leilao__pb2.LeilaoData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLeiloesAtivos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/leilao.AuctionService/GetLeiloesAtivos',
            leilao__pb2.Empty.SerializeToString,
            leilao__pb2.LeilaoData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEventos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/leilao.AuctionService/SubscribeEventos',
            leilao__pb2.Empty.SerializeToString,
            leilao__pb2.Evento.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
