# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pagamento.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pagamento.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpagamento.proto\x12\tpagamento\"D\n\x0bPaymentData\x12\x11\n\tleilao_id\x18\x01 \x01(\x05\x12\x13\n\x0bvencedor_id\x18\x02 \x01(\t\x12\r\n\x05valor\x18\x03 \x01(\x02\",\n\x06\x45vento\x12\x0c\n\x04tipo\x18\x01 \x01(\t\x12\x14\n\x0cpayload_json\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\x8b\x01\n\x0ePaymentService\x12>\n\x12ProcessarPagamento\x12\x16.pagamento.PaymentData\x1a\x10.pagamento.Empty\x12\x39\n\x10SubscribeEventos\x12\x10.pagamento.Empty\x1a\x11.pagamento.Evento0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pagamento_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAYMENTDATA']._serialized_start=30
  _globals['_PAYMENTDATA']._serialized_end=98
  _globals['_EVENTO']._serialized_start=100
  _globals['_EVENTO']._serialized_end=144
  _globals['_EMPTY']._serialized_start=146
  _globals['_EMPTY']._serialized_end=153
  _globals['_PAYMENTSERVICE']._serialized_start=156
  _globals['_PAYMENTSERVICE']._serialized_end=295
# @@protoc_insertion_point(module_scope)
